### ISSUE TITLE
config path error! looks for .spotr/config instead of .aws/config

### ISSUE THREAD

**Issue by pavanAlluri** [samuelreh/spotr#15]
As i try to launch the spot instance for fast ai, spotr, instead of looking at '.aws/config, it is looking at  .spotr/config!

I tried to change the path name in config.py file but i wasn't successful. Anyway i can change it?

**Comment by samuelreh** [comment]
Thanks for filing an issue 👍 

This should be fixed now. It will look for aws credentials and region in `~/.aws/config` and spotr specific config in `~/.spotr/config`. But if `~/.spotr/config` doesn't exist, it just uses the passed in args.

**Comment by samuelreh** [comment]
Fixed by commit: https://github.com/samuelreh/spotr/commit/0c0415815970a40be8ceb416d6e2dfa67cd9a65a
